### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by JohnPulse** [Thulinma/MixedModeAuth#17]
Hello,

Can we expect a plugin update for R6 and 1.2?
I tried to mess with the code on the Bukkit R6 but with no success..

Regards,
John

**Comment by Thulinma** [comment]
Yeah, I'll update for 1.2 sometime soon. Probably in the next few days somewhere.

**Comment by JohnPulse** [comment]
Thanks for keeping this project alive!

Just for not opening two more tickets, can you look at the possibility of making the following topics possible?
- Option to not rename players on join.
- Check if the new Bukkit API's can make so that this plugin don't need the server and the client patch.

Best regards and thanks again for your work,
John

**Comment by Thulinma** [comment]
Yeah. The first "not renaming players on join" was already on my to-do list, and will happen eventually.

The second I'm pretty sure won't ever happen... I already submitted my patch (which has hundreds of valid uses, in theory) months ago and got shot down pretty harshly. They will not allow anything that could potentially increase piracy some way. Apparently rewarding legit players on open-to-everyone-servers is increasing piracy. :-)

But who knows, maybe I'll be able to patch less? The patch is only 10 or so lines right now - maybe I can reduce it to 2 or 3 lines. I'll look into it, just to be sure.

**Comment by JohnPulse** [comment]
Thanks for your feedback.

I got another request that would be useful in my case:
- Option to make so Premium users don't need to register, but can if they want.

Regards,
John

**Comment by Thulinma** [comment]
Yeah, good idea. I'll put that in for sure.

**Comment by Ismaw34** [comment]
Hello, i played arround with the source of the client patch, and i think its posible to patch changing a few minor things.
But the source of the server mod is not released :(
I cant play around to update it myself.
Anyways, still waiting for the update.

Regards,
Ismaw34

**Comment by Thulinma** [comment]
The server source is actually released as well - you can find it in my CraftBukkit fork, here:

https://github.com/Thulinma/CraftBukkit/tree/preloginoverride

**Comment by Ismaw34** [comment]
Hello again, i compiled th server, the client and the plugin.
The server seems to work fine, but the client mod is giving black screen before downloading and loading the world when a non premium user is trying to login.
The premium user is loging in just fine.
The code seems fine, but its readapted to run the current version.

Can you help me?, and i will share my results.
Thanks, Ismaw34

Thanks,
Ismaw34

**Comment by Thulinma** [comment]
I'll look at it myself when I have time to do so - I'm pretty busy right now with other tasks, so haven't had the time to update my minecraft stuff yet. :-)

**Comment by GhoulofGSG9** [comment]
Maybe im able to help a bit.After looking over the plugin script because im using it for my testserver. I found one mistake in the class mixedmodeauth.  The problem is at Packet9respawn!(as often after majong published a new version of minecraft)
I corrected the code myself now.
Code: http://gist.github.com/2361458

Everything now works at my testserver unless offline user are not able to enter multiverse portals until i do /reload. But thats not a solution^^.

**Comment by Ismaw34** [comment]
I compiled all the things again with the lastest code.
But, the server is giving error when sending the world data to a pirated client.
The problem is the server, not the plugin or the client.
Ismaw34

**Comment by GhoulofGSG9** [comment]
Hi,
to help you at your problem i need some more information. What error is given? What have you modified at server code etc. .
But this plugin is not for pirate use!
It should be use in case you have no access to the main auth-minecraft server. Or as in my case you want to test things where you need more than one player. Because there can be only one Player at a vanilla server^^.

**Comment by Ismaw34** [comment]
Hello, BrightPaul.
This plugin is to give acces to a pirated minecraft client and let it play, another thing similar is xAuth.
The error is given by the client.

```
  Minecraft has crashed!      
  ----------------------      
```

Minecraft has stopped running because it encountered a problem.

--- BEGIN ERROR REPORT 7cf3a456 --------
Generated 12/04/12 0:29

Minecraft: Minecraft 1.2.5
OS: Windows 7 (x86) version 6.1
Java: 1.6.0_31, Sun Microsystems Inc.
VM: Java HotSpot(TM) Client VM (mixed mode), Sun Microsystems Inc.
LWJGL: 2.4.2
OpenGL: Intel 965/963 Graphics Media Accelerator version 2.0.0 - Build 8.14.10.1930, Intel

java.lang.NullPointerException
    at net.minecraft.src.World.<init>(World.java:199)
    at net.minecraft.src.WorldClient.<init>(WorldClient.java:33)
    at net.minecraft.src.NetClientHandler.handleRespawn(NetClientHandler.java:822)
    at net.minecraft.src.Packet9Respawn.processPacket(Packet9Respawn.java:37)
    at net.minecraft.src.NetworkManager.processReadPackets(NetworkManager.java:327)
    at net.minecraft.src.NetClientHandler.processReadPackets(NetClientHandler.java:54)
    at net.minecraft.src.GuiConnecting.updateScreen(GuiConnecting.java:30)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1623)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:870)
    at net.minecraft.client.Minecraft.run(Minecraft.java:801)
    at java.lang.Thread.run(Thread.java:662)
--- END ERROR REPORT d1c1f593 ----------

Im using the plugin (with your patch and without your patch) the modded server, and the modded client.
My server is stuck on 1.1 because of this. And im trying hard to fix it, but with the minimum java knowledge its nearly imposible. :(
Thanks, Ismaw34

**Comment by GhoulofGSG9** [comment]
ok just one fact: the plugin is written for 1.2.1 by thulinma and i updated it to 1.2.5. There is no way to run the current version on a server that is not 1.2.0/1 or 1.2.5! Otherwise take a look at the history of this plugin. I think there was a running version for 1.1 somewhere.
And the "patchs" for the client are also just working for the client version they are written for!

**Comment by Thulinma** [comment]
The server patch should be able to be applied to pretty much any craftbukkit version.
The client patch as well (assuming you take the source and re-patch the most current client version!)

The server plugin can work on older CB versions if you take one of the first few releases. Every plugin version works with every server/client patch version, at least so far. Newer releases of the server plugin only work on newer releases of the server, because so much has changed recently in the way plugins work. :-)

To clarify the piracy issue (again): these patches and the plugin do not make piracy any easier - all they accomplish is allowing legitimate (paying) users to use their paid-for account on servers that ALSO allow non-paid users. A great many other plugins already simply allow non-paid users - but this is the only plugin (so far) that will allow paying users to keep using their paid account at the same time. :-)

**Comment by GhoulofGSG9** [comment]
How should a older version of the plugin run with the newer version of CB while the Bukkit team changed the event system and Packet9Respawn is changed in every minecraft patch until now?

**Comment by Thulinma** [comment]
Exactly. Like I said:

> Newer releases of the server plugin only work on newer releases of the server, because so much has changed recently in the way plugins work. :-)

**Comment by GhoulofGSG9** [comment]
I just were confused about the sentence before that^^. Can you maybe take a look over the muliverse "bug" later because at the moment i have to reload to the server  at every start to fix it.

But all in all i want to thank you for your great work so far. :)
