### ISSUE TITLE
Incompatibility with latest Spout?

### ISSUE THREAD

**Issue by nordului** [Thulinma/MixedModeAuth#7]
2011-12-20 17:48:51 [INFO] This server is running Craftbukkit version git-Bukkit-1.0.1-R1-3-g626577e-b1597jnks (MC: 1.0.1+PreLogMod) (Implementing API version 1.0.1-R1)
...
2011-12-20 17:48:53 [INFO] [Spout] Spout 644 has been initialized
...
2011-12-20 17:48:55 [INFO] [MixedModeAuth] 2.4 enabled WITHOUT secure mode.
...
2011-12-20 17:48:59 [INFO] mcMMO version 1.2.07 is enabled!
...
2011-12-20 17:52:35 [SEVERE] Could not pass event BLOCK_BREAK to mcMMO
java.lang.NullPointerException
        at com.gmail.nossr50.spout.SpoutStuff.updateXpBar(SpoutStuff.java:553)
        at com.gmail.nossr50.skills.Skills.XpCheckSkill(Skills.java:360)
        at com.gmail.nossr50.skills.Herbalism.herbalismProcCheck(Herbalism.java:336)
        at com.gmail.nossr50.listeners.mcBlockListener.onBlockBreak(mcBlockListener.java:265)
        at org.bukkit.plugin.java.JavaPluginLoader$40.execute(JavaPluginLoader.java:539)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
        at net.minecraft.server.ItemInWorldManager.c(ItemInWorldManager.java:201)
        at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:145)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:498)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:208)
        at net.minecraft.server.Packet14BlockDig.a(SourceFile:43)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:93)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:550)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
2011-12-20 17:52:35 [SEVERE] Could not pass event PLAYER_INTERACT to PortalStick
java.lang.NullPointerException
        at com.matejdro.bukkit.portalstick.listeners.PortalStickPlayerListener.onPlayerInteract(PortalStickPlayerListener.java:126)
        at org.bukkit.plugin.java.JavaPluginLoader$11.execute(JavaPluginLoader.java:335)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:178)
        at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:92)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:498)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:208)
        at net.minecraft.server.Packet14BlockDig.a(SourceFile:43)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:93)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:550)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
...
2011-12-20 17:52:37 [SEVERE] Could not pass event PLAYER_MOVE to Spout
java.lang.NullPointerException
        at org.getspout.spoutapi.chunkstore.PlayerTrackingManager.onMoveChunk(PlayerTrackingManager.java:37)
        at org.getspout.spout.SpoutNetServerHandler.setPlayerChunk(SpoutNetServerHandler.java:819)
        at org.getspout.spout.SpoutPlayerListener.onPlayerMove(SpoutPlayerListener.java:218)
        at org.bukkit.plugin.java.JavaPluginLoader$7.execute(JavaPluginLoader.java:307)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:182)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:679)
        at net.minecraft.server.Packet10Flying.a(SourceFile:126)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:93)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:550)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

**Comment by Thulinma** [comment]
If this is indeed caused by MixedModeAuth, it has to do with the renaming code.
I'm planning to look into Spout compatibilty soon, will close this issue when I think it is fixed/compatible.
